# URL de la base de données créée dans XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_stages_db

# Identifiants par défaut de XAMPP (root et mot de passe vide)
spring.datasource.username=root
spring.datasource.password=

# Demande à Hibernate (l'ORM) de créer/mettre à jour les tables automatiquement
spring.jpa.hibernate.ddl-auto=update

# Permet de voir les requêtes SQL dans la console (pratique pour débugger)
spring.jpa.show-sql=true